### ISSUE TITLE
An easier way to install Vidtuber

### ISSUE THREAD

**Issue by Dragonix74** [jeanslack/Vidtuber#1]
Hello,
Is there another way to install Vidtuber? Because I find it complicated with the command lines, moreover I can't run Vidtuber because I have errors with wxpython.

**Comment by Woolwit** [comment]
It's probably worth your while to get over the hump of using it at the command line. A solid and useful skill.
pip install wxPython==4.2.0

Thank You Gianluca!

**Comment by jeanslack** [comment]
Hi everyone,

> Is there another way to install Vidtuber? Because I find it complicated with the command lines, moreover I can't run Vidtuber because I have errors with wxpython.

First I have to take the time to reorganize the project with documentation, tests and possible fixes, then I will surely do something (pypi, AppImage, Ubuntu-PPA, etc)

**Comment by Dragonix74** [comment]
> It's probably worth your while to get over the hump of using it at the command line. A solid and useful skill. pip install wxPython==4.2.0
> 
> Thank You Gianluca!

It's when I use pip install wxPython==4.2.0 that I get errors.

**Comment by jeanslack** [comment]
@Woolwit @Dragonix74 

Update:
Sorry for wasting your time, take this as a joke if you like, but I'm happy to report that I managed to re-implement once again the yt-dlp GUI on Videomass. So this repository is totally useless and obsolete. Videomass has already been released today, I hope it repays you for this disappointment.

**Comment by Woolwit** [comment]
No worries! Awesome that it's working in Videomass! Thanks again!!

**Comment by ioc2e3** [comment]
> It's probably worth your while to get over the hump of using it at the command line. ...

However ...

not everyone has such a good memory ...

not everyone is able to make typing errors ...

.
